spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data-consumer
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: localhost:9092
  topic: complex-events
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  group-id: my-group
  partition: 0


logging:
  level:
    root: INFO
    com.example.consumer: DEBUG

software:
  internal: 12452627367627643

