spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/external-data
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: localhost:9092
  topic: complex-events
  producer:
    acks: all
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    com.example.producer: DEBUG

server:
  port: 8081

software:
  internal: 12452627367627643



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.myapp
  paths-to-match: /**
